name: Trigger Jenkins Job

on:
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - master
#     paths-ignore:
#       - 'README.md'
    
jobs:
  trigger:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.URL }}
          user: ${{ secrets.USER }}
          token: ${{ secrets.TOKEN }}
          job: ${{ secrets.JOBS }}